"""Configuration file for Sphinx."""

# pylint: disable = invalid-name, empty-comment
#
# Spyder API docs documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  9 13:47:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.


# Standard library imports
import datetime
import os
import sys
from pathlib import Path

# Third party imports
from docutils import nodes
from docutils.parsers.rst import Directive, directives


# Constants
UTC_DATE = datetime.datetime.now(datetime.timezone.utc)

# Make Spyder available on $PATH for API documentation
sys.path.insert(0, str(Path(__file__).parents[1].resolve() / "spyder"))


# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
needs_sphinx = "6.2"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named "sphinx.ext.*") or your custom ones.
extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.githubpages",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "Spyder Developer Docs"
author = "Spyder-API-Docs Contributors"
copyright = (  # pylint: disable = redefined-builtin
    f" 2020-{UTC_DATE.year} {author}; MIT License"
)

# The version info for the project you"re documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = "6"
# The full version, including alpha/beta/rc tags.
release = "6"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Intersphinx configuration
# pylint: disable-next = consider-using-namedtuple-or-dataclass
intersphinx_mapping = {
    "python": ("https://docs.python.org/", None),
    "PyQt5": ("https://www.riverbankcomputing.com/static/Docs/PyQt5/", None),
    "spyder": ("https://docs.spyder-ide.org/current/", None),
}

# Warning suppression
suppress_warnings = []

# Nitpick warning ignore list
nitpick_ignore_regex = {
    # Spyder modules currently not included in the build
    (
        "py:.+",
        # pylint: disable-next = line-too-long
        "spyder.(app|config|fonts|images|locale|plugins|tests|utils|widgets|windows).*",  # noqa: E501
    ),
    # Numpydoc optional
    ("py:class", "optional"),
    # Typing params
    ("py:.+", ".*_P"),
    ("py:.+", ".*_RT"),
    ("py:.+", ".*_T"),
    # Cannot use type aliases to fix refs inside type aliases or class bases
    ("py:class", "asyncio.events.AbstractEventLoop"),
    ("py:class", "concurrent.futures._base.Future"),
    # Type aliases don't work properly in Sphinx <9
    ("py:class", "BasicTypes"),
    ("py:class", "spyder.api.config.mixins.BasicTypes"),
    ("py:class", "ConfigurationKeyOrList"),
    ("py:class", "spyder.api.config.decorators.ConfigurationKeyOrList"),
    ("py:class", "LoopID"),
    ("py:class", "OptionSet"),
    ("py:class", "spyder.api.preferences.OptionSet"),
    ("py:class", "SpyderPluginClass"),
    ("py:class", "spyder.api.plugin_registration.registry.SpyderPluginClass"),
}


# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_book_theme"

# Theme options are theme-specific and customize the look and feel of a
# theme further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "repository_url": "https://github.com/spyder-ide/spyder-api-docs",
    "use_repository_button": True,
    "use_issues_button": True,
    "use_edit_page_button": True,
}
html_logo = "_static/images/spyder_logo.svg"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "_static/favicon.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]


# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "spyder_api_doc"


# -- Options for LaTeX output ------------------------------------------

latex_elements = {
    # The paper size ("letterpaper" or "a4paper").
    #
    # "papersize": "letterpaper",
    #
    # The font size ("10pt", "11pt" or "12pt").
    #
    # "pointsize": "10pt",
    #
    # Additional stuff for the LaTeX preamble.
    #
    # "preamble": "",
    #
    # Latex figure (float) alignment
    #
    # "figure_align": "htbp",
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass
# [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "spyder_api_docs.tex",
        project,
        author,
        "manual",
    ),
]


# -- Options for manual page output ------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        master_doc,
        "spyder_api_docs",
        project,
        [author],
        1,
    )
]


# -- Options for Texinfo output ----------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "spyder_api_docs",
        project,
        author,
        "spyder_api_docs",
        "The developer docs for the Spyder scientific Python IDE.",
        "Miscellaneous",
    ),
]

# source_parsers = {
#    ".md": "recommonmark.parser.CommonMarkParser",
# }


# -- Options for Linkcheck ---------------------------------------------

linkcheck_ignore = [
    # Virtual fragment ids
    r"https://(www\.)?github\.com/.+/compare/.+#diff-.+",
    # Flaky
    r"https://(www\.)?packages\.gentoo\.org/?.*",
    r"https://(www\.)?software\.opensuse\.org/?.*",
    r"https://(www\.)?packages\.ubuntu\.com/?.*",
    r"https://(www\.)?github\.com/.+/commit/.+",
    r"https://(www\.)?figshare\.com/?.*",
    # Blocks GitHub Actions
    r"https://(www\.)?(\w+\.)?reddit\.com/?.*",
    r"https://(www\.)?(\w+\.)?(stackoverflow|stackexchange)\.com/?.*",
]


# --- Myst parser options
# See: https://myst-parser.readthedocs.io/
myst_config = {}


# -- Options for Autodoc/Autosummary -----------------------------------

# Include Python objects as they appear in source files
# Default: alphabetically ('alphabetical')
autodoc_member_order = "bysource"

# Default flags used by autodoc directives
autodoc_default_options = {
    "members": True,
    "private-members": "_",
    "special-members": True,
    "exclude-members": "__weakref__",
    "show-inheritance": True,
}

# Disable imports that cause crashes
autodoc_mock_imports = [
    # "qtpy.QtGui",
    # "qdarkstyle",
    # "qstylizer",
]

# Configure type aliases for signatures
autodoc_type_aliases = {
    # Actual type aliases
    "BasicTypes": "spyder.api.config.mixins.BasicTypes",
    "ConfigurationKey": "spyder.config.types.ConfigurationKey",
    "ConfigurationKeyList": (
        "spyder.api.config.decorators.ConfigurationKeyList"
    ),
    "ConfigurationKeyOrList": (
        "spyder.api.config.decorators.ConfigurationKeyOrList"
    ),
    "LoopID": "spyder.api.asyncdispatcher.LoopID",
    "OptionSet": "spyder.api.preferences.OptionSet",
    "SpyderPluginClass": (
        "spyder.api.plugin_registration.registry.SpyderPluginClass"
    ),
    # Ref name aliases
    "AbstractEventLoop": "asyncio.AbstractEventLoop",
    "asyncio.AbstractEventLoop": "asyncio.AbstractEventLoop",
    "asyncio.events.AbstractEventLoop": "asyncio.AbstractEventLoop",
    "Future": "concurrent.futures.Future",
    "concurrent.futures.Future": "concurrent.futures.Future",
    "concurrent.futures._base.Future": "concurrent.futures.Future",
}

# Monkeypatch to fix type aliases not working in classmethods with Sphinx
# See sphinx-doc/sphinx#10333
# pylint: disable-next = wrong-import-position
from sphinx.util import inspect  # noqa: E402

inspect.TypeAliasForwardRef.__repr__ = lambda self: self.name
inspect.TypeAliasForwardRef.__hash__ = lambda self: hash(self.name)

# Set list of modules and patterns to ignore in the autosummary template
autosummary_context = {
    "ignore_module_pattern": "tests",
    "ignore_modules": [
        "spyder.api.editor",
        "spyder.api.plugins.enum",
        "spyder.api.plugins.new_api",
        "spyder.api.plugins.tests",
    ],
}

# Generate autosummaries if the autodoc tag is passed
# pylint: disable-next = undefined-variable
if "autodoc" in tags:  # noqa: F821
    autosummary_generate = True
    os.environ["SPHINX_AUTODOC"] = "1"
    extensions.append("sphinx_qt_documentation")  # Errors out w/o Qt installed
else:
    autosummary_generate = False
    exclude_patterns += ["reference.rst"]
    suppress_warnings += ["autodoc", "autosummary", "toc.excluded"]


# -- Additional Directives ---------------------------------------------------

# ReST directive for embedding Youtube and Vimeo videos.
# There are two directives added: ``youtube`` and ``vimeo``. The only
# argument is the video id of the video to include.
# Both directives have three optional arguments: ``height``, ``width``
# and ``align``. Default height is 281 and default width is 500.
# Example::
#     .. youtube:: anwy2MPT5RE
#         :height: 315
#         :width: 560
#         :align: left
# :copyright: (c) 2012 by Danilo Bargen.
# :license: BSD 3-clause


def align(argument):
    """Convert the "align" argument to one of the specified options."""
    return directives.choice(argument, ("left", "center", "right"))


class IFrameVideo(Directive):
    """A general directive for injecting an iframe video in a Sphinx doc."""

    has_content = False
    required_arguments = 1
    optional_arguments = 0
    final_argument_whitespace = False
    option_spec = {
        "height": directives.nonnegative_int,
        "width": directives.nonnegative_int,
        "align": align,
        "start": directives.nonnegative_int,
    }
    default_width = 500
    default_height = 281
    default_start = 0

    def run(self):
        """Execute the iframe video directive."""
        self.options["video_id"] = directives.uri(self.arguments[0])
        if not self.options.get("width"):
            self.options["width"] = self.default_width
        if not self.options.get("height"):
            self.options["height"] = self.default_height
        if not self.options.get("align"):
            self.options["align"] = "left"
        if not self.options.get("start"):
            self.options["start"] = self.default_start
        return [nodes.raw("", self.html % self.options, format="html")]


class Youtube(IFrameVideo):
    """A specific directive for injecting a Youtube video in a Sphinx doc."""

    html = "".join(
        [
            '<div class="video-container-container">',
            '<div class="video-container">',
            '<iframe src="https://www.youtube.com/embed/%(video_id)s',
            '?start=%(start)s" ',
            'width="%(width)u" height="%(height)u" frameborder="0" ',
            "webkitAllowFullScreen mozallowfullscreen allowfullscreen ",
            'class="align-%(align)s"></iframe></div></div>',
        ]
    )


def setup(builder):  # pylint: disable = unused-argument
    """Register directives with Sphinx."""
    directives.register_directive("youtube", Youtube)
